name: Build fouldecrypt

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        provider: [TFP0, LIBKRW, LIBKERNRW]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        brew install make
        brew install ldid
        brew install dpkg
        brew install theos

    - name: Build package
      shell: bash
      run: |
        rm -f packages/*
        cp control.template control

        PROVIDER="${{ matrix.provider }}"

        # Theos / SDK / compiler setup
        export THEOS=$GITHUB_WORKSPACE/theos
        export SDKROOT=$(xcrun --sdk iphoneos --show-sdk-path)
        export CC=clang
        export CXX=clang++
        export CPLUS_INCLUDE_PATH=$(xcrun --show-sdk-path)/usr/include/c++/v1
        export TARGET_IOS=13.0
        export TARGET_ARCH=arm64e

        if [[ "$PROVIDER" == "TFP0" ]]; then
          USE_TFP0=1 make -j$(sysctl -n hw.ncpu) package FINALPACKAGE=1
        elif [[ "$PROVIDER" == "LIBKRW" ]]; then
          sed -i '' 's/{{.depends}}/libkrw/g' control
          USE_LIBKRW=1 make -j$(sysctl -n hw.ncpu) package FINALPACKAGE=1
        elif [[ "$PROVIDER" == "LIBKERNRW" ]]; then
          sed -i '' 's/{{.depends}}/libkernrw0/g' control
          USE_LIBKERNRW=1 make -j$(sysctl -n hw.ncpu) package FINALPACKAGE=1
        fi

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: packages
        path: packages/*.deb
