name: Build Fouldecrypt

# Trigger the workflow manually or on push to main
on:
  workflow_dispatch:    # Manual run button
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    env:
      THEOS: /Users/runner/work/fouldecrypt/fouldecrypt/theos
      SDKROOT: /Applications/Xcode_16.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.0.sdk
      CC: clang
      CXX: clang++

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew install make ldid dpkg

      - name: Build packages
        shell: bash
        run: |
          rm -f packages/*
          cp control.template control

          PROVIDER="TFP0"

          if [[ "$PROVIDER" == "TFP0" ]]; then
            USE_TFP0=1 make -j$(sysctl -n hw.ncpu) package FINALPACKAGE=1
          elif [[ "$PROVIDER" == "LIBKRW" ]]; then
            sed -i '' 's/{{.depends}}/libkrw/g' control
            USE_LIBKRW=1 make -j$(sysctl -n hw.ncpu) package FINALPACKAGE=1
          elif [[ "$PROVIDER" == "LIBKERNRW" ]]; then
            sed -i '' 's/{{.depends}}/libkernrw0/g' control
            USE_LIBKERNRW=1 make -j$(sysctl -n hw.ncpu) package FINALPACKAGE=1
          fi
