name: C/C++ CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        provider: [TFP0, LIBKRW, LIBKERNRW]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Prepare Theos
        uses: Randomblock1/theos-action@v1

      - name: Build package
        shell: bash
        run: |
          rm -f packages/*
          cp control.template control

          PROVIDER="${{ matrix.provider }}"

          # Theos / SDK / compiler setup
          export THEOS=$GITHUB_WORKSPACE/theos
          export SDKROOT=/Applications/Xcode_16.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.0.sdk
          export CC=clang
          export CXX=clang++
          export CPLUS_INCLUDE_PATH=/Applications/Xcode_16.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1
          export TARGET_IOS=13.0
          export TARGET_ARCH=arm64e

          if [[ "$PROVIDER" == "TFP0" ]]; then
            USE_TFP0=1 make -j$(sysctl -n hw.ncpu) package FINALPACKAGE=1
          elif [[ "$PROVIDER" == "LIBKRW" ]]; then
            sed -i '' 's/{{.depends}}/libkrw/g' control
            USE_LIBKRW=1 make -j$(sysctl -n hw.ncpu) package FINALPACKAGE=1
          elif [[ "$PROVIDER" == "LIBKERNRW" ]]; then
            sed -i '' 's/{{.depends}}/libkernrw0/g' control
            USE_LIBKERNRW=1 make -j$(sysctl -n hw.ncpu) package FINALPACKAGE=1
          fi

      - name: Publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: fouldecrypt-${{ matrix.provider }}
          path: ${{ github.workspace }}/packages/*.deb

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ github.workspace }}/packages/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
