name: Build Fouldecrypt

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Homebrew
        run: |
          echo "::group::Homebrew Setup"
          if ! command -v brew &> /dev/null; then
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          fi
          echo "::endgroup::"

      - name: Install dependencies
        run: |
          echo "::group::Installing Dependencies"
          brew install make gpatch libmd ldid dpkg || true
          echo "Adding GNU make to PATH..."
          echo "/opt/homebrew/opt/make/libexec/gnubin" >> $GITHUB_PATH
          echo "::endgroup::"

      - name: Setup Xcode command line tools
        run: |
          echo "::group::Xcode CLI Tools"
          sudo xcode-select --install || true
          sudo xcode-select -s /Applications/Xcode_16.app/Contents/Developer
          echo "::endgroup::"

      - name: Set THEOS environment
        run: |
          echo "::group::Set THEOS Environment"
          export THEOS="$GITHUB_WORKSPACE/theos"
          echo "THEOS=$THEOS" >> $GITHUB_ENV
          echo "::endgroup::"

      - name: Build packages
        run: |
          echo "::group::Build Fouldecrypt Packages"
          rm -f packages/*
          cp control.template control

          PROVIDER="TFP0"
          if [[ "$PROVIDER" == "TFP0" ]]; then
            USE_TFP0=1 gmake -j$(sysctl -n hw.ncpu) package FINALPACKAGE=1
          elif [[ "$PROVIDER" == "LIBKRW" ]]; then
            sed -i '' 's/{{.depends}}/libkrw/g' control
            USE_LIBKRW=1 gmake -j$(sysctl -n hw.ncpu) package FINALPACKAGE=1
          elif [[ "$PROVIDER" == "LIBKERNRW" ]]; then
            sed -i '' 's/{{.depends}}/libkernrw0/g' control
            USE_LIBKERNRW=1 gmake -j$(sysctl -n hw.ncpu) package FINALPACKAGE=1
          fi
          echo "::endgroup::"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: fouldecrypt-packages
          path: packages/*
