name: Build Theos Project

on:
  workflow_dispatch:   # manual trigger
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Install dependencies
      - name: Install Homebrew dependencies
        run: |
          brew install make ldid dpkg gpatch libmd

      # 3. Set up Theos
      - name: Set up Theos
        run: |
          export THEOS=$HOME/theos
          git clone --depth=1 https://github.com/theos/theos.git $THEOS
          echo "THEOS=$THEOS" >> $GITHUB_ENV

      # 4. Make sure GNU make is used
      - name: Use gmake if needed
        run: |
          echo 'export PATH="/opt/homebrew/opt/make/libexec/gnubin:$PATH"' >> $GITHUB_ENV

      # 5. Build the project
      - name: Build with Theos
        run: |
          export THEOS=$THEOS
          make clean
          make

      # 6. Optional: Archive build artifacts
      - name: Archive .deb or build output
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: deb-package
          path: ./packages/*.deb
